name: Release-plz Trezu CLI

permissions:
  pull-requests: write
  contents: write

on: workflow_dispatch

jobs:
  # Release unpublished packages.
  release-plz-release:
    name: Release-plz release
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'NEAR-DevHub' }}
    permissions:
      contents: write
      pull-requests: read
    steps:
      - &checkout
        name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          persist-credentials: false
      - &install-rust
        name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Install packages (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install --assume-yes libudev-dev
      - name: Run release-plz
        id: release-plz
        uses: release-plz/action@v0.5
        with:
          command: release
          manifest_path: nt-cli/Cargo.toml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
    outputs:
      release_created: ${{ steps.release-plz.outputs.releases_created }}
      release_tag: ${{ fromJSON(steps.release-plz.outputs.releases)[0].version }}

  create-binary-release:
    uses: ./.github/workflows/cli-release.yml
    needs: release-plz-release
    if: ${{ needs.release-plz-release.outputs.release_created }}
    permissions:
      contents: write
      id-token: write
    secrets: inherit
    with:
      tag: ${{ needs.release-plz-release.outputs.release_tag }}


  # Create a PR with the new versions and changelog, preparing the next release.
  # (disabled since we have a monorepo)
  #release-plz-pr:
  #  name: Release-plz PR
  #  runs-on: ubuntu-latest
  #  permissions:
  #    contents: write
  #    pull-requests: write
  #  concurrency:
  #    group: release-plz-${{ github.ref }}
  #    cancel-in-progress: false
  #  steps:
  #    - *checkout
  #    - *install-rust
  #    - name: Run release-plz
  #      uses: release-plz/action@v0.5
  #      with:
  #        command: release-pr
  #      env:
  #        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
